#!/usr/bin/env zsh
# install.sh — Entry point for system setup
# Usage: ./install.sh [hostname] [flags]
#
# Flags:
#   --dry-run, --plan        Show what would happen without changing anything.
#   --only packages|dotfiles Restrict scope.
#   --yes, -y                Skip the diff confirmation prompt.
#   --no-preview             Skip the diff preview entirely.
#   --upgrade                Also upgrade outdated Homebrew packages (default: install only).
#   --cleanup                Also remove unlisted Homebrew formulae/casks (DESTRUCTIVE).
#
# Env vars:
#   BREW_UPGRADE=1   same as --upgrade
#   BREW_CLEANUP=1   same as --cleanup
set -euo pipefail

if [[ -n "${ZSH_VERSION:-}" ]]; then
    setopt typeset_silent
fi

_script_path() {
    if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
        echo "${BASH_SOURCE[0]}"
    elif [[ -n "${funcfiletrace[1]:-}" ]]; then
        echo "${funcfiletrace[1]%:*}"
    else
        echo "$0"
    fi
}

SETUP_DIR="$(cd "$(dirname "$(_script_path)")" && pwd)"
export SETUP_DIR

# Parse arguments
HOSTNAME_ARG=""
DRY_RUN=0
ONLY=""
ASSUME_YES=0
SHOW_PREVIEW=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run|--plan) DRY_RUN=1 ;;
        --yes|-y) ASSUME_YES=1 ;;
        --no-preview) SHOW_PREVIEW=0 ;;
        --only=*) ONLY="${1#--only=}" ;;
        --only) shift; ONLY="${1:-}" ;;
        --upgrade) BREW_UPGRADE=1 ;;
        --cleanup) BREW_CLEANUP=1 ;;
        -*) echo "Unknown flag: $1" >&2; exit 1 ;;
        *)  HOSTNAME_ARG="$1" ;;
    esac
    shift
done

# Carry through to lib/brew.sh.
BREW_UPGRADE="${BREW_UPGRADE:-0}"
BREW_CLEANUP="${BREW_CLEANUP:-0}"
export DRY_RUN BREW_UPGRADE BREW_CLEANUP

HOSTNAME="${HOSTNAME_ARG:-$(hostname -s)}"
STATE_ROOT="${SETUP_STATE_ROOT:-${HOME}/.setupstate}"
STATE_DIR="${STATE_ROOT}"
export HOSTNAME STATE_DIR STATE_ROOT

# Load helpers
source "${SETUP_DIR}/lib/utils.sh"

prepare_state_root() {
    ensure_dir "${STATE_ROOT}"

    local notice_file="${STATE_ROOT}/README_DO_NOT_EDIT.txt"
    if [[ ! -f "${notice_file}" ]]; then
        if [[ "${DRY_RUN}" == "1" ]]; then
            log_dry "create ${notice_file}"
        else
            cat > "${notice_file}" <<'EOF'
This directory is auto-generated by the setup scripts.
Do not edit files here manually unless you know exactly what you are doing.
EOF
        fi
    fi
}

migrate_legacy_state_files() {
    # New layout is flat: ${STATE_ROOT}/*.txt
    # Legacy layouts:
    #   1) ~/.setup-state/<host>/*.txt
    #   2) ~/.setup-state/*.txt
    #   3) <STATE_ROOT>/<host>/*.txt
    local -a legacy_dirs
    legacy_dirs=(
        "${HOME}/.setup-state/${HOSTNAME}"
        "${HOME}/.setup-state"
        "${STATE_ROOT}/${HOSTNAME}"
    )

    local legacy_dir file base target
    for legacy_dir in "${legacy_dirs[@]}"; do
        [[ -d "${legacy_dir}" ]] || continue

        while IFS= read -r file; do
            [[ -n "${file}" ]] || continue
            base="$(basename "${file}")"
            target="${STATE_ROOT}/${base}"

            if [[ "${file}" == "${target}" ]]; then
                continue
            fi
            if [[ -f "${target}" ]]; then
                continue
            fi

            if [[ "${DRY_RUN}" == "1" ]]; then
                log_dry "cp ${file} ${target}"
            else
                cp "${file}" "${target}"
                log_info "Migrated legacy state: ${base}"
            fi
        done < <(find "${legacy_dir}" -maxdepth 1 -type f -name '*.txt' 2>/dev/null || true)
    done
}

prepare_state_root
migrate_legacy_state_files

log_section "Setup: ${HOSTNAME}"
[[ "${DRY_RUN}" == "1" ]] && log_warn "Dry-run mode — no changes will be made"

# Load host config (sets BREWS, CASKS, PACKAGES, DOTFILES, etc.)
HOST_FILE="${SETUP_DIR}/hosts/${HOSTNAME}.sh"
if [[ ! -f "$HOST_FILE" ]]; then
    log_error "No host config found for '${HOSTNAME}' at ${HOST_FILE}"
    exit 1
fi
source "$HOST_FILE"
OS="$(uname)"
HOST_EXTRA_LIB="${SETUP_DIR}/lib/host-${HOSTNAME}.sh"
if [[ -f "${HOST_EXTRA_LIB}" ]]; then
    source "${HOST_EXTRA_LIB}"
fi

SUDO_KEEPALIVE_PID=""

start_sudo_keepalive() {
    if [[ -n "${SUDO_KEEPALIVE_PID}" ]]; then
        return
    fi

    # Keep sudo ticket fresh during long installs (e.g. Homebrew casks).
    while true; do
        sudo -n true >/dev/null 2>&1 || exit 0
        sleep 50
    done &
    SUDO_KEEPALIVE_PID=$!
}

stop_sudo_keepalive() {
    if [[ -z "${SUDO_KEEPALIVE_PID}" ]]; then
        return
    fi

    kill "${SUDO_KEEPALIVE_PID}" >/dev/null 2>&1 || true
    wait "${SUDO_KEEPALIVE_PID}" 2>/dev/null || true
    SUDO_KEEPALIVE_PID=""
}

maybe_prime_sudo_session() {
    if [[ "${DRY_RUN}" == "1" ]]; then
        return
    fi
    if [[ "${OS}" != "Darwin" ]]; then
        return
    fi
    if [[ ! -t 0 || ! -t 1 ]]; then
        log_warn "Non-interactive terminal: skip sudo pre-auth."
        return
    fi

    log_section "Sudo session"
    log_info "Requesting admin password once for this run..."
    sudo -v
    start_sudo_keepalive
    trap stop_sudo_keepalive EXIT INT TERM
}

maybe_preview_and_confirm() {
    # Only prompt in real execution with an interactive terminal.
    if [[ "${DRY_RUN}" == "1" || "${ASSUME_YES}" == "1" || "${SHOW_PREVIEW}" == "0" ]]; then
        return
    fi
    if [[ ! -t 0 || ! -t 1 ]]; then
        return
    fi

    log_section "Planned changes (diff preview)"
    if [[ -n "${ONLY}" ]]; then
        log_info "Preview scope: ${ONLY}"
    else
        log_info "Preview scope: packages + dev-tools + macOS defaults + dotfiles"
    fi

    local has_changes=0

    if [[ -z "${ONLY}" || "${ONLY}" == "packages" ]]; then
        if [[ "${OS}" == "Darwin" ]]; then
            source "${SETUP_DIR}/lib/brew.sh"
            source "${SETUP_DIR}/lib/dev-tools.sh"
            source "${SETUP_DIR}/lib/macos.sh"

            if ! preview_brew_changes; then
                has_changes=1
            fi
            if ! preview_dev_tools_changes; then
                has_changes=1
            fi
            if ! preview_macos_defaults_changes; then
                has_changes=1
            fi
            if typeset -f preview_host_extras_changes >/dev/null; then
                if ! preview_host_extras_changes; then
                    has_changes=1
                fi
            fi
        else
            log_warn "Diff preview for Linux packages is not implemented yet."
        fi
    fi

    if [[ -z "${ONLY}" || "${ONLY}" == "dotfiles" ]]; then
        source "${SETUP_DIR}/lib/dotfiles.sh"
        if ! preview_dotfiles_changes; then
            has_changes=1
        fi
    fi

    if (( has_changes == 0 )); then
        log_info "No changes detected."
    fi

    echo
    printf "Proceed with real execution for host '%s'? [y/N]: " "${HOSTNAME}"
    local answer
    IFS= read -r answer
    case "$answer" in
        y|Y|yes|YES) ;;
        *)
            log_warn "Aborted by user."
            exit 1
            ;;
    esac
}

maybe_preview_and_confirm

maybe_prime_sudo_session

# --- Packages ---
if [[ -z "$ONLY" || "$ONLY" == "packages" ]]; then
    if [[ "$OS" == "Darwin" ]]; then
        source "${SETUP_DIR}/lib/brew.sh"
        source "${SETUP_DIR}/lib/dev-tools.sh"
        source "${SETUP_DIR}/lib/macos.sh"
        install_brew_deps
        if typeset -f sync_host_extras >/dev/null; then
            sync_host_extras
        fi
        sync_brew_packages
        setup_dev_tool_env
        sync_go_install_tools
        sync_uv_tools
        sync_pnpm_global_packages
        sync_git_lfs
        sync_macos_defaults
    else
        source "${SETUP_DIR}/lib/pacman.sh"
        sync_pacman_packages
        sync_systemd_services
    fi
fi

# --- Dotfiles ---
if [[ -z "$ONLY" || "$ONLY" == "dotfiles" ]]; then
    source "${SETUP_DIR}/lib/dotfiles.sh"
    sync_dotfiles
fi

log_section "Done"
