#!/usr/bin/env zsh
# lib/brew.sh — macOS Homebrew package management
#
# Design:
#   * Single source of truth: `brew bundle check / install / cleanup`.
#     No custom "is this installed" logic — it gets cask vs formula vs tap wrong.
#   * Foreground execution. brew prints its own download / install progress;
#     backgrounding hid that for 10+ minutes and broke sudo prompts.
#   * Conservative defaults:
#       install  -> only missing packages (--no-upgrade)
#                   set BREW_UPGRADE=1 (or pass --upgrade) to also upgrade outdated
#       cleanup  -> off
#                   set BREW_CLEANUP=1 (or pass --cleanup) to remove unlisted packages
#
# Two text files are maintained in $STATE_DIR — both are real Brewfiles:
#
#   Brewfile           Desired state. Translated from the host config and
#                      regenerated on every run. This is the input passed to
#                      `brew bundle`. Re-runnable by hand:
#                          brew bundle install --file=~/.setupstate/Brewfile
#
#   brew_bundle.txt    Last successfully-synced snapshot. Only updated after
#                      `brew bundle install` (and optional cleanup) succeed.
#                      Diff against Brewfile to see drift between desired and
#                      last-applied state.

BREWFILE_PATH="${STATE_ROOT:-${HOME}/.setupstate}/Brewfile"
BREW_STATE_FILE="${STATE_ROOT:-${HOME}/.setupstate}/brew_bundle.txt"

_detect_brew_bin() {
    if command -v brew &>/dev/null; then
        command -v brew
    elif [[ -x /opt/homebrew/bin/brew ]]; then
        echo "/opt/homebrew/bin/brew"
    elif [[ -x /usr/local/bin/brew ]]; then
        echo "/usr/local/bin/brew"
    else
        echo ""
    fi
}

_write_brewfile() {
    local file="$1"

    : > "$file"
    {
        echo "# Auto-generated by .dotfiles/install.sh"
        echo "# Host: ${HOSTNAME:-unknown}    Generated: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# Edit hosts/${HOSTNAME:-<host>}.sh, not this file."
        echo
        local item
        for item in "${BREWS[@]:-}"; do
            [[ -n "$item" ]] && printf 'brew "%s"\n' "$item"
        done
        for item in "${CASKS[@]:-}"; do
            [[ -n "$item" ]] && printf 'cask "%s"\n' "$item"
        done
        for item in "${FONT_CASKS[@]:-}"; do
            [[ -n "$item" ]] && printf 'cask "%s"\n' "$item"
        done
    } >> "$file"
}

# Print pending changes without applying them.
# Returns 0 if nothing actionable, 1 if changes pending.
_preview_brew_changes() {
    local file="$1"
    local pending=0

    # --- Install plan ---
    # `brew bundle check --verbose` prints "→ Cask X needs to be installed."
    # / "→ Formula X needs to be installed." / "→ X needs to be upgraded."
    # and exits 1 when not satisfied.
    local check_output check_exit
    local -a check_flags
    check_flags=(--verbose --file="$file")
    [[ "${BREW_UPGRADE:-0}" != "1" ]] && check_flags+=(--no-upgrade)

    check_output="$(brew bundle check "${check_flags[@]}" 2>&1)"
    check_exit=$?

    if (( check_exit == 0 )); then
        log_info "Install plan: nothing to do."
    else
        pending=1
        if [[ "${BREW_UPGRADE:-0}" == "1" ]]; then
            log_info "Install plan (install missing + upgrade outdated):"
        else
            log_info "Install plan (install missing only — set BREW_UPGRADE=1 to also upgrade):"
        fi
        echo "$check_output" \
            | grep -E "needs to be (installed|upgraded)" \
            | sed 's/^→ /  /'
    fi

    # --- Cleanup plan ---
    # Without --force, `brew bundle cleanup` is a dry-run.
    local cleanup_output cleanup_exit
    cleanup_output="$(brew bundle cleanup --formula --cask --file="$file" 2>&1)"
    cleanup_exit=$?

    local has_cleanup=0
    if (( cleanup_exit != 0 )) || echo "$cleanup_output" | grep -q "Would "; then
        has_cleanup=1
    fi

    if (( has_cleanup == 0 )); then
        log_info "Cleanup plan: nothing to remove."
    else
        if [[ "${BREW_CLEANUP:-0}" == "1" ]]; then
            log_info "Cleanup plan (WILL REMOVE on apply):"
            pending=1
        else
            log_info "Cleanup plan (skipped — set BREW_CLEANUP=1 to actually remove):"
        fi
        # brew bundle cleanup output is flat — header lines start with "Would ",
        # item lines are bare package names. Nest items under their headers.
        echo "$cleanup_output" \
            | grep -v "^Run \`brew bundle cleanup --force\`" \
            | awk '/^Would / {print "  " $0; next} NF {print "      " $0} !NF {print}'
    fi

    return $(( pending == 0 ? 0 : 1 ))
}

preview_brew_changes() {
    log_section "Homebrew packages (diff)"

    local brew_bin
    brew_bin="$(_detect_brew_bin)"
    if [[ -z "$brew_bin" ]]; then
        log_info "Homebrew not installed yet — full install will run on apply."
        local item
        for item in "${BREWS[@]:-}"; do
            [[ -n "$item" ]] && echo "  + brew $item"
        done
        for item in "${CASKS[@]:-}"; do
            [[ -n "$item" ]] && echo "  + cask $item"
        done
        for item in "${FONT_CASKS[@]:-}"; do
            [[ -n "$item" ]] && echo "  + cask $item"
        done
        return 1
    fi

    ensure_dir "$(dirname "$BREWFILE_PATH")"
    _write_brewfile "$BREWFILE_PATH"
    log_info "Brewfile: $BREWFILE_PATH"

    _preview_brew_changes "$BREWFILE_PATH"
}

_has_xcode_clt() {
    xcode-select -p &>/dev/null && \
        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables &>/dev/null
}

ensure_xcode_clt() {
    log_section "Xcode Command Line Tools"

    if _has_xcode_clt; then
        log_info "Xcode Command Line Tools already installed."
        return 0
    fi

    if [[ "${DRY_RUN:-}" == "1" ]]; then
        log_dry "xcode-select --install"
        log_dry "wait until xcode-select -p succeeds"
        return 0
    fi

    log_info "Xcode Command Line Tools not found. Starting installation..."
    local output
    output="$(xcode-select --install 2>&1 || true)"
    [[ -n "$output" ]] && echo "$output"

    if _has_xcode_clt; then
        log_info "Xcode Command Line Tools ready."
        return 0
    fi

    log_warn "Waiting for Command Line Tools installation to finish..."
    local timeout_sec=5400
    local step_sec=10
    local elapsed=0
    while ! _has_xcode_clt; do
        sleep "$step_sec"
        elapsed=$((elapsed + step_sec))
        if (( elapsed >= timeout_sec )); then
            log_error "Timed out waiting for Xcode Command Line Tools."
            return 1
        fi
    done

    log_info "Xcode Command Line Tools ready."
}

_persist_brew_shellenv() {
    local brew_bin="$1"
    local profile="${HOME}/.zprofile"
    local line="eval \"\$(${brew_bin} shellenv)\""

    if [[ "${DRY_RUN:-}" == "1" ]]; then
        log_dry "touch ${profile}"
        log_dry "append '${line}' to ${profile} (if missing)"
        return
    fi

    touch "$profile"
    if ! grep -Fq "$line" "$profile"; then
        printf '\n%s\n' "$line" >> "$profile"
        log_info "Added Homebrew shellenv to ${profile}"
    fi
}

install_brew_deps() {
    ensure_xcode_clt

    local brew_bin
    brew_bin="$(_detect_brew_bin)"

    if [[ -z "$brew_bin" ]]; then
        log_info "Homebrew not found. Installing..."
        run /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew_bin="$(_detect_brew_bin)"
    fi

    if [[ -z "$brew_bin" ]]; then
        log_error "Homebrew installation appears incomplete: brew binary not found."
        return 1
    fi

    if [[ "${DRY_RUN:-}" != "1" ]]; then
        eval "$("${brew_bin}" shellenv)"
    fi
    _persist_brew_shellenv "$brew_bin"

    log_info "Homebrew ready: $("${brew_bin}" --version | head -1)"
}

_save_brew_state_snapshot() {
    # Snapshot the just-applied Brewfile, with a header line marking when.
    # Used as the audit trail of "what's currently on the system, as far as
    # this script knows."
    if [[ "${DRY_RUN:-}" == "1" ]]; then
        log_dry "snapshot ${BREWFILE_PATH} -> ${BREW_STATE_FILE}"
        return
    fi
    {
        echo "# Last successful sync: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# Host: ${HOSTNAME:-unknown}"
        echo "# Generated by .dotfiles/install.sh — diff against Brewfile to see drift."
        echo
        # Strip the desired-state header so the file is a clean Brewfile.
        sed '/^# Auto-generated/,/^$/d' "$BREWFILE_PATH"
    } > "$BREW_STATE_FILE"
}

sync_brew_packages() {
    log_section "Homebrew packages"
    ensure_dir "$(dirname "$BREWFILE_PATH")"
    _write_brewfile "$BREWFILE_PATH"
    log_info "Desired state:    $BREWFILE_PATH"
    log_info "Last-applied:     $BREW_STATE_FILE"

    local -a install_flags
    install_flags=(--file="$BREWFILE_PATH" --verbose)
    [[ "${BREW_UPGRADE:-0}" != "1" ]] && install_flags+=(--no-upgrade)

    if [[ "${DRY_RUN:-}" == "1" ]]; then
        log_dry "brew bundle install ${install_flags[*]}"
        if [[ "${BREW_CLEANUP:-0}" == "1" ]]; then
            log_dry "brew bundle cleanup --force --formula --cask --file=$BREWFILE_PATH"
        fi
        log_dry "snapshot ${BREWFILE_PATH} -> ${BREW_STATE_FILE} (on success)"
        return
    fi

    if [[ "${BREW_UPGRADE:-0}" == "1" ]]; then
        log_info "brew bundle install (install missing + upgrade outdated)"
    else
        log_info "brew bundle install --no-upgrade (install missing only)"
    fi
    log_info "Streaming brew output below — Ctrl-C aborts safely:"
    echo

    local install_start install_end
    install_start=$SECONDS
    # Foreground: brew prints its own progress; sudo prompts work; Ctrl-C is honoured.
    if ! brew bundle install "${install_flags[@]}"; then
        log_error "brew bundle install failed (after $((SECONDS - install_start))s)."
        log_error "Re-run by hand to debug: brew bundle install ${install_flags[*]}"
        log_error "State snapshot NOT updated; ${BREW_STATE_FILE} still reflects last good run."
        return 1
    fi
    install_end=$SECONDS
    log_info "brew bundle install completed in $((install_end - install_start))s."

    if [[ "${BREW_CLEANUP:-0}" == "1" ]]; then
        log_warn "brew bundle cleanup --force (removing unlisted formulae/casks)"
        echo
        local cleanup_start
        cleanup_start=$SECONDS
        if ! brew bundle cleanup --force --formula --cask --file="$BREWFILE_PATH"; then
            log_error "brew bundle cleanup failed (after $((SECONDS - cleanup_start))s)."
            log_error "State snapshot NOT updated; ${BREW_STATE_FILE} still reflects last good run."
            return 1
        fi
        log_info "brew bundle cleanup completed in $((SECONDS - cleanup_start))s."
    else
        log_info "Skipped cleanup. Set BREW_CLEANUP=1 (or pass --cleanup) to remove unlisted packages."
    fi

    _save_brew_state_snapshot
    log_info "State snapshot updated: $BREW_STATE_FILE"
}
